version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_APP_NAME=AWP React Platform
      - NEXT_PUBLIC_APP_VERSION=0.1.0
    volumes:
      - ./public:/app/public
    restart: unless-stopped

  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_NAME=AWP React Platform (Dev)
      - NEXT_PUBLIC_APP_VERSION=0.1.0
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    profiles:
      - dev
